function loadGraphics()
    Bahnschrift_sm = love.graphics.newFont("/fonts/BAHNSCHRIFT.TTF", 30)
    Bahnschrift_lg = love.graphics.newFont("/fonts/BAHNSCHRIFT.TTF", 100)

    PlayerBody = love.graphics.newImage("images/player_body.png")
    PlayerIdle = love.graphics.newImage("images/player_idle.png")
    PlayerStep1 = love.graphics.newImage("images/player_step_1.png")
    PlayerStep2 = love.graphics.newImage("images/player_step_2.png")
    PlayerRise = love.graphics.newImage("images/player_rising.png")
    PlayerFall = love.graphics.newImage("images/player_falling.png")
    PlayerSlide = love.graphics.newImage("images/player_slide.png")

    local tiles_references = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "13", "14", "17", "18", "19", "21", "22", "23", "24", "26", "27", "28", "29"}
    WTiles = {}
    STiles = {}
    for i=1,29 do
        for _, j in ipairs(tiles_references) do
            if tostring(i) == j then
                table.insert(WTiles, love.graphics.newImage("images/"..i..".png"))
                table.insert(STiles, love.graphics.newImage("images/s"..i..".png"))
                break
            end 
        end
        if WTiles[i] == nil then
            table.insert(WTiles, love.graphics.newImage("images/invalid.png"))
            table.insert(STiles, love.graphics.newImage("images/invalid.png"))
        end
    end

    Arrow = love.graphics.newImage("images/arrow.png")
    Switch = love.graphics.newImage("images/switch.png")
end

function loadAudio()
    -- Sound Effects generated by https://sfxr.me/
    Step = love.audio.newSource("sounds/step2.wav", "static")
    Bump = love.audio.newSource("sounds/bump.wav", "static")
    JumpSound = love.audio.newSource("sounds/jump.wav", "static")
    SmallLanding = love.audio.newSource("sounds/landing_small.wav", "static")
    LargeLanding = love.audio.newSource("sounds/landing_large.wav", "static")
    Slide = love.audio.newSource("sounds/slide.wav", "static")
    Slide:setLooping(true)
    Walljump = love.audio.newSource("sounds/walljump.wav", "static")
    SwitchSound = love.audio.newSource("sounds/switch.wav", "static")
    SwitchMeter = love.audio.newSource("sounds/switch_meter.wav", "static")
    SwitchMeter:setLooping(true)
    SwitchReady = love.audio.newSource("sounds/switch_ready.wav", "static")
    Pause = love.audio.newSource("sounds/pause.wav", "static")
    Unpause = love.audio.newSource("sounds/unpause.wav", "static")
end