-- Function to load all of the images and fonts
function loadGraphics()
    -- Load two different font types (used in the pause menu)
    Bahnschrift_sm = love.graphics.newFont("/fonts/BAHNSCHRIFT.TTF", 30) -- Small, 30pt font
    Bahnschrift_lg = love.graphics.newFont("/fonts/BAHNSCHRIFT.TTF", 100) -- Large, 100pt font

    -- Load all player sprites
    PlayerBody = love.graphics.newImage("images/player_body.png")
    PlayerIdle = love.graphics.newImage("images/player_idle.png")
    PlayerStep1 = love.graphics.newImage("images/player_step_1.png")
    PlayerStep2 = love.graphics.newImage("images/player_step_2.png")
    PlayerRise = love.graphics.newImage("images/player_rising.png")
    PlayerFall = love.graphics.newImage("images/player_falling.png")
    PlayerSlide = love.graphics.newImage("images/player_slide.png")

    -- Create tables for World tiles, Special (sol/lua) tiles, and Decor tiles
    WTiles = {}
    STiles = {}
    DTiles = {}
    -- Go through each number 1-30 and add the tiles to memory
    for i=1,30 do
        -- If the current tile exists for World tiles, load the World and Special tile
        if love.filesystem.getInfo("images/"..i..".png") then
            table.insert(WTiles, love.graphics.newImage("images/"..i..".png"))
            table.insert(STiles, love.graphics.newImage("images/s"..i..".png"))
        -- If not, load a special image for invalid sprites (hopefully never seen in game)
        else
            table.insert(WTiles, love.graphics.newImage("images/invalid.png"))
            table.insert(STiles, love.graphics.newImage("images/invalid.png"))
        end
        -- If the current tile exists for Decor tiles, load the Decor sprites
        if love.filesystem.getInfo("images/d"..i..".png") then
            table.insert(DTiles, love.graphics.newImage("images/d"..i..".png"))
        -- If not, load the invalid image sprite
        else
            table.insert(DTiles, love.graphics.newImage("images/invalid.png"))
        end
    end

    -- Load pause menu graphics
    Arrow = love.graphics.newImage("images/arrow.png")
    Switch = love.graphics.newImage("images/switch.png")
end

-- Function to load all of the sound effects
function loadAudio()
    -- Sound Effects generated by https://sfxr.me/
    Step = love.audio.newSource("sounds/step2.wav", "static") -- Footstep
    Bump = love.audio.newSource("sounds/bump.wav", "static") -- Bump into a wall
    JumpSound = love.audio.newSource("sounds/jump.wav", "static") -- Jump sound
    SmallLanding = love.audio.newSource("sounds/landing_small.wav", "static") -- Land from a short fall
    LargeLanding = love.audio.newSource("sounds/landing_large.wav", "static") -- Land for a high fall
    Slide = love.audio.newSource("sounds/slide.wav", "static") -- Sliding on a wall
    Slide:setLooping(true) -- Slide sound will loop whenever it plays
    Walljump = love.audio.newSource("sounds/walljump.wav", "static") -- Wall jump
    SwitchSound = love.audio.newSource("sounds/switch.wav", "static") -- Full switch sound
    SwitchMeter = love.audio.newSource("sounds/switch_meter.wav", "static") -- Switch charging sound
    SwitchMeter:setLooping(true) -- Charging sound will loop
    SwitchReady = love.audio.newSource("sounds/switch_ready.wav", "static") -- Ping when switch meter has stopped falling
    SwitchWarning = love.audio.newSource("sounds/switch_warning.wav", "static") -- Warning sound when player would switch into an opposite-phase block
    Pause = love.audio.newSource("sounds/pause.wav", "static") -- Pause the game
    Unpause = love.audio.newSource("sounds/unpause.wav", "static") -- Unpause the game
end